name: Continuous Integration
on:
  pull_request:
    paths-ignore: 
      - 'README.md'
  push:
    paths-ignore: 
      - 'README.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build test container
        shell: bash
        run: |
          docker build --target test --tag todo-app:test .

      - name: Run tests
        shell: bash
        run: |
          docker run todo-app:test
  
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push docker image to registry
        shell: bash
        run: |
          docker build --target production --tag ${{secrets.DOCKER_HUB_USER}}/todo-app:${{github.sha}} .
          docker build --target production --tag ${{secrets.DOCKER_HUB_USER}}/todo-app:latest .
          docker push ${{secrets.DOCKER_HUB_USER}}/todo-app:${{github.sha}}
          docker push ${{secrets.DOCKER_HUB_USER}}/todo-app:latest

      - name: Deploy image to web app
        run: curl -dH -X POST '${{secrets.AZURE_WEBHOOK}}'
